name: windowstests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

permissions:
  contents: read

jobs:
  tests:
    name: windowstests
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v4

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Build
        run: python setup.py build_ext --inplace

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: ${{ matrix.os }}
          path: build/lib.win-amd64-cpython-311/decrypt.cp311-win_amd64.pyd